<?php

/**
 * Implements hook_page_button();
 *
 * Add valet markup to the top of the page automatically.
 */
function valet_page_top(array &$page_top) {
  $page_top['valet'] = array(
    '#type' => 'valet',
    '#weight' => -100,
    '#access' => \Drupal::currentUser()->hasPermission('access valet'),
  );
}

/**
 * Implements hook_theme().
 */
function valet_theme() {
  return array(
    'valet' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Prepares variables for administration toolbar templates.
 *
 * Default template: toolbar.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties and children of
 *     the tray. Properties used: #children, #attributes and #bar.
 */
function template_preprocess_valet(&$variables) {
  $element = $variables['element'];

  // Prepare valet attributes.
  $variables['attributes'] = $element['#attributes'];
}
