<?php

/**
 * Implements hook_page_buttom();
 *
 * Add valet markup to the bottom of the page automatically.
 */
function valet_page_bottom(array &$page_bottom) {
  $page_bottom['valet'] = array(
    '#type' => 'valet',
    '#access' => \Drupal::currentUser()->hasPermission('access valet'),
    '#cache' => [
      'keys' => ['valet'],
      'contexts' => ['user.permissions'],
    ],
  );
}

/**
 * Implements hook_theme().
 */
function valet_theme() {
  return array(
    'valet' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Prepares variables for administration toolbar templates.
 *
 * Default template: valet.html.twig.
 *
 * @param array $vars
 *   An associative array containing:
 *   - element: An associative array containing the properties and children of
 *     the tray. Properties used: #children, #attributes and #bar.
 */
function template_preprocess_valet(&$vars) {
  $element = $vars['element'];
  // Prepare valet attributes.
  $vars['attributes'] = $element['#attributes'];
}
